/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Cluster;



/**
 *
 * @author kittylon
 */
public class verClusters extends javax.swing.JFrame {

    /**
     * Creates new form verClusters
     */
    public verClusters() {
        initComponents();
        this.setSize(1000, 600);
        //recuperar todos los ids de dibujo para mostrar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIdDibujo = new javax.swing.JLabel();
        jComboBoxIdDibujo = new javax.swing.JComboBox();
        jLabelIdConjunto = new javax.swing.JLabel();
        jLabelCondGen = new javax.swing.JLabel();
        jLabelCondParada = new javax.swing.JLabel();
        jButtonVerCluster = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jLabelGeneracion = new javax.swing.JLabel();
        jLabelParada = new javax.swing.JLabel();
        jScrollPaneGrafica = new javax.swing.JScrollPane();
        jPanelGrafica = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelIdDibujo.setText("Id Dibujo");

        jComboBoxIdDibujo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelIdConjunto.setText("Id conjunto:");

        jLabelCondGen.setText("Condición de Generación:");

        jLabelCondParada.setText("Condición de Parada:");

        jButtonVerCluster.setText("Ver Clúster");
        jButtonVerCluster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerClusterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCondParada)
                    .addComponent(jLabelCondGen)
                    .addComponent(jLabelIdConjunto)
                    .addComponent(jLabelIdDibujo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxIdDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelId)
                    .addComponent(jLabelGeneracion)
                    .addComponent(jLabelParada))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVerCluster)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdDibujo)
                    .addComponent(jComboBoxIdDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdConjunto)
                    .addComponent(jLabelId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCondGen)
                    .addComponent(jLabelGeneracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCondParada)
                    .addComponent(jLabelParada))
                .addGap(24, 24, 24)
                .addComponent(jButtonVerCluster)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneGrafica.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jScrollPaneGraficaComponentMoved(evt);
            }
        });

        jPanelGrafica.setMinimumSize(new java.awt.Dimension(9990, 9990));
        jPanelGrafica.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jPanelGraficaComponentMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanelGraficaLayout = new javax.swing.GroupLayout(jPanelGrafica);
        jPanelGrafica.setLayout(jPanelGraficaLayout);
        jPanelGraficaLayout.setHorizontalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9990, Short.MAX_VALUE)
        );
        jPanelGraficaLayout.setVerticalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9990, Short.MAX_VALUE)
        );

        jScrollPaneGrafica.setViewportView(jPanelGrafica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneGrafica)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneGrafica)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerClusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerClusterActionPerformed
        jLabelId.setText("recuperar info");
        jLabelGeneracion.setText("recuperar info");
        jLabelParada.setText("recuperar info");   
        jScrollPaneGrafica.getVerticalScrollBar().setValue(9990);
        SquaredPaper DrawWindow = new SquaredPaper();
        DrawWindow.paint(jPanelGrafica);
    }//GEN-LAST:event_jButtonVerClusterActionPerformed

    private void jScrollPaneGraficaComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPaneGraficaComponentMoved

        
    }//GEN-LAST:event_jScrollPaneGraficaComponentMoved

    private void jPanelGraficaComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelGraficaComponentMoved
        //jScrollPaneGrafica.getVerticalScrollBar().setValue(9990);
        SquaredPaper_1_1 DrawWindow = new SquaredPaper_1_1();
        DrawWindow.paint(jPanelGrafica);
    }//GEN-LAST:event_jPanelGraficaComponentMoved

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVerCluster;
    private javax.swing.JComboBox jComboBoxIdDibujo;
    private javax.swing.JLabel jLabelCondGen;
    private javax.swing.JLabel jLabelCondParada;
    private javax.swing.JLabel jLabelGeneracion;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIdConjunto;
    private javax.swing.JLabel jLabelIdDibujo;
    private javax.swing.JLabel jLabelParada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGrafica;
    private javax.swing.JScrollPane jScrollPaneGrafica;
    // End of variables declaration//GEN-END:variables
}
